import type {
  HarnessEvent,
  IdentitySource,
  PermissionResult,
  SessionStoreConfig,
  UserMessage,
} from "@computeragent/protocol";
import type { Substrate } from "./substrate.js";

/** Convenience: any input shape accepted by `agent.chat()`. */
export type ChatInput =
  | string
  | UserMessage
  | UserMessage[]
  | AsyncIterable<UserMessage>;

/** Decision returned from a user-supplied `onToolCall` callback. */
export type PermissionDecision =
  | { decision: "allow"; input?: Record<string, unknown> }
  | { decision: "deny"; reason?: string }
  | { decision: "modify"; input: Record<string, unknown> };

/** Argument passed to a user `onToolCall` callback. */
export interface ToolCallContext {
  readonly callId: string;
  readonly toolName: string;
  readonly input: unknown;
  readonly risk?: "low" | "medium" | "high" | "destructive";
}

/** Configuration the user passes to `new ComputerAgent({...})`. */
export interface ComputerAgentOptions {
  /** GAP source — git URL, local path, or inline manifest. */
  readonly source: IdentitySource | string;
  /** Engine name registered on the harness server (e.g. "claude-agent-sdk", "gitagent"). */
  readonly harness: string;
  /** Identity loader name (defaults to "gitagentprotocol"). */
  readonly identityLoader?: string;
  /**
   * WHERE the harness server runs. Three forms:
   *   - omitted / "local" → `harnessUrl` (default localhost:7700)
   *   - a Substrate object → SDK calls `bootHarness()` on first chat()
   *   - any other string → opaque label for future built-in substrates
   */
  readonly runtime?: "local" | Substrate | (string & {});
  /** Override the harness server URL. Defaults to `http://127.0.0.1:7700`. */
  readonly harnessUrl?: string;
  /** Env vars passed to the engine (e.g. ANTHROPIC_API_KEY). */
  readonly envs?: Readonly<Record<string, string>>;
  /** Optional explicit session id. Auto-generated by the server otherwise. */
  readonly sessionId?: string;
  /** Engine-specific options forwarded as `body.options` (model, maxTurns, permissionMode, …). */
  readonly options?: Readonly<Record<string, unknown>>;
  /** HITL callback. If omitted, ca_permission_request events are auto-allowed. */
  readonly onToolCall?: (call: ToolCallContext) => Promise<PermissionDecision> | PermissionDecision;
  /** Custom fetch (for testing or proxy). */
  readonly fetch?: typeof fetch;
  /**
   * Optional swappable SessionStore for conversation persistence. The server
   * resolves the `kind` via its registry (built-in: `"memory"`, `"file"`;
   * custom kinds registered via `createHarnessServer({ sessionStores })`).
   *
   * Combined with `sessionId`, this enables resume across process restarts:
   * pass the same store config + sessionId, the engine loads prior entries
   * and continues. Pass without a known sessionId to start a fresh persisted
   * session.
   */
  readonly sessionStore?: SessionStoreConfig;
}

/** Resolved final outcome of a chat turn (or chained turns drained via `.run()`). */
export interface ChatResult {
  readonly sessionId: string;
  /** Forwarded engine messages collected during the turn. */
  readonly messages: ReadonlyArray<unknown>;
  /** Terminal `ca_session_ended` event. */
  readonly ended: Extract<HarnessEvent, { kind: "ca_session_ended" }>;
}

/** Map our SDK PermissionDecision to the wire body shape. */
export function decisionToBody(d: PermissionDecision): {
  decision: "allow" | "deny" | "modify";
  input?: unknown;
  reason?: string;
} {
  if (d.decision === "deny") {
    const reason = d.reason ?? "denied";
    return { decision: "deny", reason };
  }
  if (d.decision === "modify") return { decision: "modify", input: d.input };
  return d.input ? { decision: "allow", input: d.input } : { decision: "allow" };
}

/** Re-export the wire-side PermissionResult for advanced users that want the raw shape. */
export type { PermissionResult };
