import type {
  HarnessEvent,
  IdentitySource,
  PermissionResult,
  SessionStoreConfig,
  UserMessage,
} from "@computeragent/protocol";
import type { Substrate } from "./substrate.js";

/** Convenience: any input shape accepted by `agent.chat()`. */
export type ChatInput =
  | string
  | UserMessage
  | UserMessage[]
  | AsyncIterable<UserMessage>;

/**
 * Engine names shipped with this SDK. The actual set the harness accepts is
 * decided at server boot via `createHarnessServer({ engines })`, so this
 * type accepts any string — built-ins are listed for autocomplete only.
 *
 * The `(string & {})` clause prevents TS from collapsing the union to plain
 * `string` (which would lose the autocomplete) while still permitting any
 * custom engine name a downstream user might register.
 *
 * Add a new built-in engine by extending this union here AND by registering
 * it at the harness boot site. New third-party engines need no SDK change —
 * just pass the string they registered.
 */
export type HarnessName =
  | "claude-agent-sdk"
  | "gitagent"
  | (string & {});

/** Identity loaders shipped with this SDK. Same open-set semantics as `HarnessName`. */
export type IdentityLoaderName =
  | "gitagentprotocol"
  | (string & {});

/**
 * Session-store kinds the harness's default registry knows about. Custom kinds
 * registered via `createHarnessServer({ sessionStores })` are accepted too.
 * (E.g. `@computeragent/session-store-mongo` and `-sqlite` register their own.)
 */
export type SessionStoreKind =
  | "memory"
  | "file"
  | (string & {});

/** Decision returned from a user-supplied `onToolCall` callback. */
export type PermissionDecision =
  | { decision: "allow"; input?: Record<string, unknown> }
  | { decision: "deny"; reason?: string }
  | { decision: "modify"; input: Record<string, unknown> };

/** Argument passed to a user `onToolCall` callback. */
export interface ToolCallContext {
  readonly callId: string;
  readonly toolName: string;
  readonly input: unknown;
  readonly risk?: "low" | "medium" | "high" | "destructive";
}

/** Configuration the user passes to `new ComputerAgent({...})`. */
export interface ComputerAgentOptions {
  /** GAP source — git URL, local path, or inline manifest. */
  readonly source: IdentitySource | string;
  /**
   * Engine name registered on the harness server. Built-ins shipped with this
   * SDK: `"claude-agent-sdk"`, `"gitagent"`. Custom engines registered via
   * `createHarnessServer({ engines })` are accepted too — the field is open
   * to extension.
   */
  readonly harness: HarnessName;
  /** Identity loader name. Built-in: `"gitagentprotocol"`. Defaults to that. */
  readonly identityLoader?: IdentityLoaderName;
  /**
   * WHERE the harness server runs. Three forms:
   *   - omitted / "local" → `harnessUrl` (default localhost:7700)
   *   - a Substrate object → SDK calls `bootHarness()` on first chat()
   *   - any other string → opaque label for future built-in substrates
   */
  readonly runtime?: "local" | Substrate | (string & {});
  /** Override the harness server URL. Defaults to `http://127.0.0.1:7700`. */
  readonly harnessUrl?: string;
  /** Env vars passed to the engine (e.g. ANTHROPIC_API_KEY). */
  readonly envs?: Readonly<Record<string, string>>;
  /** Optional explicit session id. Auto-generated by the server otherwise. */
  readonly sessionId?: string;
  /** Engine-specific options forwarded as `body.options` (model, maxTurns, permissionMode, …). */
  readonly options?: Readonly<Record<string, unknown>>;
  /** HITL callback. If omitted, ca_permission_request events are auto-allowed. */
  readonly onToolCall?: (call: ToolCallContext) => Promise<PermissionDecision> | PermissionDecision;
  /** Custom fetch (for testing or proxy). */
  readonly fetch?: typeof fetch;
  /**
   * Optional swappable SessionStore for conversation persistence. The server
   * resolves the `kind` via its registry (built-in: `"memory"`, `"file"`;
   * custom kinds registered via `createHarnessServer({ sessionStores })`).
   *
   * Combined with `sessionId`, this enables resume across process restarts:
   * pass the same store config + sessionId, the engine loads prior entries
   * and continues. Pass without a known sessionId to start a fresh persisted
   * session.
   */
  readonly sessionStore?: SessionStoreConfig;
}

/**
 * Aggregated token + cost telemetry for a chat turn.
 *
 * Tokens are summed across every `ca_usage_snapshot` event the engine emits
 * during the turn (each engine snapshot is per-message; the SDK adds them up).
 *
 * `costUsd` follows the engine's `costSemantic`:
 *   - "cumulative" (Claude Agent SDK): we take the MAX seen value
 *   - "delta" (gitclaw):                we SUM the per-message values
 *
 * `undefined` for any field means the engine didn't emit it. Cost is
 * undefined when the underlying provider doesn't return cost — never
 * computed client-side from a price table (issue #5).
 */
export interface UsageRollup {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cacheCreationInputTokens: number;
  readonly cacheReadInputTokens: number;
  readonly costUsd: number | undefined;
}

/** Resolved final outcome of a chat turn (or chained turns drained via `.run()`). */
export interface ChatResult {
  readonly sessionId: string;
  /** Forwarded engine messages collected during the turn. */
  readonly messages: ReadonlyArray<unknown>;
  /** Terminal `ca_session_ended` event. */
  readonly ended: Extract<HarnessEvent, { kind: "ca_session_ended" }>;
  /**
   * Token + cost rollup for this turn. Zeros for token counts and `undefined`
   * for `costUsd` when the engine didn't emit any usage snapshots (e.g. a
   * mock engine, or an error before the first LLM call).
   */
  readonly usage: UsageRollup;
}

/** Map our SDK PermissionDecision to the wire body shape. */
export function decisionToBody(d: PermissionDecision): {
  decision: "allow" | "deny" | "modify";
  input?: unknown;
  reason?: string;
} {
  if (d.decision === "deny") {
    const reason = d.reason ?? "denied";
    return { decision: "deny", reason };
  }
  if (d.decision === "modify") return { decision: "modify", input: d.input };
  return d.input ? { decision: "allow", input: d.input } : { decision: "allow" };
}

/** Re-export the wire-side PermissionResult for advanced users that want the raw shape. */
export type { PermissionResult };
